# -*- coding: utf-8 -*-
"""Lab_Session_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAgcJD3cHwc0SODFiCyAkwKBV352MRLc
"""

from google.colab import drive
import pandas as pd
import numpy as np
drive.mount('/content/drive')
purchase_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Lab Session Data.xlsx', usecols=[0,1, 2, 3,4])
print("PURCHASE DATA:")
print(purchase_data)
data1=purchase_data.iloc[:, 1:4]
A = data1.to_numpy()
print("MATRIX A:")
print(A)
data1=purchase_data.iloc[:, 4:5]
C = data1.to_numpy()
print("MATRIX C:")
print(C)
print("DIMENSIONALITY OF VECTOR SPACE OF DATA:\n",len(A[0]))
print("NO.OF VECTOR SPACES:\n",len(A))
rank_A=np.linalg.matrix_rank(A)
print("RANK OF MATRIX A:\n",rank_A)
pseudo_inverse_A=np.linalg.pinv(A)
print("PSEUDO INVERSE OF A:\n",pseudo_inverse_A)
print(A)
